name: common-ci-cd

on: [push, pull_request]

jobs:
    all:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Install Depedencies
              run: make install

            - name: Run Typecheck
              run: make typecheck

            - name: Run Linter
              run: make lint-src

            - name: Run Format Check
              run: make format-check

            - name: Run Tests
              run: |
                  make test
                  rm -rf __test__

            - name: Run Build
              run: make build
